library("Amelia")
library("MatchIt")
library("Zelig")
library("dplyr")
library("ggplot2")
library("RColorBrewer")
library("xlsx")
library("optmatch")
library("reshape2")
library("readxl")

ratings <- read.table("/home/niharika-shimona/Documents/Projects/Netflix_Challenge/ml-20m/ratings.csv",header = TRUE, sep = ",")
genres <- read_excel("/home/niharika-shimona/Documents/Projects/Netflix_Challenge/ml-20m/movies.xlsx")
ratings <- merge(ratings, genres, "movieId")
write.csv(ratings,"/home/niharika-shimona/Documents/Projects/Netflix_Challenge/ml-20m/movies_genre.csv")